# Generated by Django 5.2.1 on 2025-05-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('sent', 'Message Sent'), ('replied', 'User Replied'), ('reminded', 'Reminder Sent'), ('completed', 'Onboarding Completed')], default='sent', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
