# Generated by Django 5.2.1 on 2025-05-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_candidate_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
