# Generated by Django 5.2.1 on 2025-06-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_candidate_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
